#############################################################
######    Begin of Makefile
#############################################################

SCADE=C:\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\.

SHELL=cmd.exe

C_FLAGS = -O2 -pedantic

all: CheckBGInputChannel_Pkg__Listen_on_BTM.exe CheckBGInputChannel_Pkg__Listen_on_BTM.dll 

win32/Listen_on_BTM_CheckBGInputChannel_Pkg.o: Listen_on_BTM_CheckBGInputChannel_Pkg.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "Listen_on_BTM_CheckBGInputChannel_Pkg.c" -o "win32\Listen_on_BTM_CheckBGInputChannel_Pkg.o"

win32/CAST_N_PIG_to_int_TM_conversions.o: CAST_N_PIG_to_int_TM_conversions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "CAST_N_PIG_to_int_TM_conversions.c" -o "win32\CAST_N_PIG_to_int_TM_conversions.o"

win32/CAST_N_TOTAL_to_int_TM_conversions.o: CAST_N_TOTAL_to_int_TM_conversions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "CAST_N_TOTAL_to_int_TM_conversions.c" -o "win32\CAST_N_TOTAL_to_int_TM_conversions.o"

win32/CAST_NID_BG_to_int_TM_conversions.o: CAST_NID_BG_to_int_TM_conversions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "CAST_NID_BG_to_int_TM_conversions.c" -o "win32\CAST_NID_BG_to_int_TM_conversions.o"

win32/Consistency_Check_Track_BG_Subfunctions.o: Consistency_Check_Track_BG_Subfunctions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "Consistency_Check_Track_BG_Subfunctions.c" -o "win32\Consistency_Check_Track_BG_Subfunctions.o"

win32/CAST_Int_to_N_PIG_TM_conversions.o: CAST_Int_to_N_PIG_TM_conversions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "CAST_Int_to_N_PIG_TM_conversions.c" -o "win32\CAST_Int_to_N_PIG_TM_conversions.o"

win32/Decop_Received_BG_Subfunctions.o: Decop_Received_BG_Subfunctions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "Decop_Received_BG_Subfunctions.c" -o "win32\Decop_Received_BG_Subfunctions.o"

win32/InitBG_Subfunctions.o: InitBG_Subfunctions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "InitBG_Subfunctions.c" -o "win32\InitBG_Subfunctions.o"

win32/Pack_Received_BG_Subfunctions.o: Pack_Received_BG_Subfunctions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "Pack_Received_BG_Subfunctions.c" -o "win32\Pack_Received_BG_Subfunctions.o"

win32/Decop_Track_Msg_Subfunctions.o: Decop_Track_Msg_Subfunctions.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "Decop_Track_Msg_Subfunctions.c" -o "win32\Decop_Track_Msg_Subfunctions.o"

win32/kcg_types.o: kcg_types.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "kcg_types.c" -o "win32\kcg_types.o"

win32/kcg_consts.o: kcg_consts.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "kcg_consts.c" -o "win32\kcg_consts.o"

win32/CheckBGInputChannel_newtype.o: CheckBGInputChannel_newtype.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "CheckBGInputChannel_newtype.c" -o "win32\CheckBGInputChannel_newtype.o"

win32/CheckBGInputChannel_newmapping.o: CheckBGInputChannel_newmapping.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "CheckBGInputChannel_newmapping.c" -o "win32\CheckBGInputChannel_newmapping.o"

win32/CheckBGInputChannel_newinterface.o: CheckBGInputChannel_newinterface.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "CheckBGInputChannel_newinterface.c" -o "win32\CheckBGInputChannel_newinterface.o"

win32/SmuProxy.o: C:/Program\ Files\ (x86)/Esterel\ Technologies/SCADE\ R15.2/SCADE/lib/SmuProxy.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "C:\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\lib\SmuProxy.c" -o "win32\SmuProxy.o"

win32/NewSmuTypes.o: C:/Program\ Files\ (x86)/Esterel\ Technologies/SCADE\ R15.2/SCADE/lib/NewSmuTypes.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "C:\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\lib\NewSmuTypes.c" -o "win32\NewSmuTypes.o"

win32/SmuConverter.o: C:/Program\ Files\ (x86)/Esterel\ Technologies/SCADE\ R15.2/SCADE/lib/SmuConverter.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "C:\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\lib\SmuConverter.c" -o "win32\SmuConverter.o"

CheckBGInputChannel_Pkg__Listen_on_BTM.dll: win32/Listen_on_BTM_CheckBGInputChannel_Pkg.o win32/CAST_N_PIG_to_int_TM_conversions.o win32/CAST_N_TOTAL_to_int_TM_conversions.o win32/CAST_NID_BG_to_int_TM_conversions.o win32/Consistency_Check_Track_BG_Subfunctions.o win32/CAST_Int_to_N_PIG_TM_conversions.o win32/Decop_Received_BG_Subfunctions.o win32/InitBG_Subfunctions.o win32/Pack_Received_BG_Subfunctions.o win32/Decop_Track_Msg_Subfunctions.o win32/kcg_types.o win32/kcg_consts.o win32/CheckBGInputChannel_newtype.o win32/CheckBGInputChannel_newmapping.o win32/CheckBGInputChannel_newinterface.o win32/SmuProxy.o win32/NewSmuTypes.o win32/SmuConverter.o SmuExport.def 
	gcc -mwindows -mwin32 -shared -static-libgcc  "win32\Listen_on_BTM_CheckBGInputChannel_Pkg.o" "win32\CAST_N_PIG_to_int_TM_conversions.o" "win32\CAST_N_TOTAL_to_int_TM_conversions.o" "win32\CAST_NID_BG_to_int_TM_conversions.o" "win32\Consistency_Check_Track_BG_Subfunctions.o" "win32\CAST_Int_to_N_PIG_TM_conversions.o" "win32\Decop_Received_BG_Subfunctions.o" "win32\InitBG_Subfunctions.o" "win32\Pack_Received_BG_Subfunctions.o" "win32\Decop_Track_Msg_Subfunctions.o" "win32\kcg_types.o" "win32\kcg_consts.o" "win32\CheckBGInputChannel_newtype.o" "win32\CheckBGInputChannel_newmapping.o" "win32\CheckBGInputChannel_newinterface.o" "win32\SmuProxy.o" "win32\NewSmuTypes.o" "win32\SmuConverter.o" -Wl,--output-def,"SmuExport.def" -lm -lwsock32 -o "CheckBGInputChannel_Pkg__Listen_on_BTM.dll" 

SmuExport.def: C:/Program\ Files\ (x86)/Esterel\ Technologies/SCADE\ R15.2/SCADE/lib/SmuExport.def
	copy "C:\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\lib\SmuExport.def" "SmuExport.def"

win32/Listen_on_BTM_CheckBGInputChannel_Pkg_dll.o: Listen_on_BTM_CheckBGInputChannel_Pkg_dll.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "Listen_on_BTM_CheckBGInputChannel_Pkg_dll.c" -o "win32\Listen_on_BTM_CheckBGInputChannel_Pkg_dll.o"

win32/SmuMainWindows.o: C:/Program\ Files\ (x86)/Esterel\ Technologies/SCADE\ R15.2/SCADE/lib/SmuMainWindows.c
	gcc -I"." -I"$(SCADE)" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\include" -I"..\..\..\..\..\..\..\..\..\..\..\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\libraries\libmathext" $(C_FLAGS) -DBUILD_DLL -DSIM -DWIN32 -D_CONSOLE -D_MBCS -c "C:\Program Files (x86)\Esterel Technologies\SCADE R15.2\SCADE\lib\SmuMainWindows.c" -o "win32\SmuMainWindows.o"

CheckBGInputChannel_Pkg__Listen_on_BTM.exe: win32/Listen_on_BTM_CheckBGInputChannel_Pkg_dll.o win32/SmuMainWindows.o 
	gcc "win32\Listen_on_BTM_CheckBGInputChannel_Pkg_dll.o" "win32\SmuMainWindows.o" -lm -lwsock32 -o "CheckBGInputChannel_Pkg__Listen_on_BTM.exe" 

#############################################################
######    End of Makefile
#############################################################
