#OBJ: Ori

#DIR=../
#OBJ = $(addprefix $(DIR)$</, *.c) FORCE#DIR=../Original
#DIR=../Modified
#DIR=../Modified2
#DIR=../Modified3
#DIR=../Sources
FILETYPE= c

# make sure that the BOOST libraries (in particular dynamic_bitset) is in the include path
CPPFLAGS += -I.
CXXFLAGS = -Wall -pedantic -std=c++11
CFLAGS = -Wall -pedantic -std=c11

#vpath %.$(FILETYPE)  $($@_DIR)

all: clean test_bitwalker FORCE
	./test_bitwalker

Original:
	$(eval CPPFLAGS += -I../$@)
	$(eval VPATH := ../$@)
	echo "dir  $(VPATH)";
	echo "var $@"
	$(CXX) -o $@ $+
	$(MAKE) test_bitwalker




test_bitwalker:    test_bitwalker.o Bitwalker.o
	$(CXX) -o $@ $+


format:
	@astyle -A1 -f -p -Y -z2 -c --indent=spaces -s4  *.cpp

clean:
	@$(RM) test_bitwalker
	@$(RM) *.o
	@$(RM) *.orig

FORCE:

