/* $*************** KCG Version 6.1.3 (build i6) ****************
** Command: s2c613 -config D:/User/bw1stws0/text/z_OpenETCS/muell/muell_09/b-ScadeModel/SCADE_Procedure_OS_Systerel/KCG\kcg_s2c_config.txt
** Generation date: 2013-10-16T13:43:10
*************************************************************$ */

#include "kcg_consts.h"
#include "kcg_sensors.h"
#include "M01_A00_EXTRACT_DATAS_IN.h"

/* M01_A00_EXTRACT_DATAS_IN */
void M01_A00_EXTRACT_DATAS_IN(
  /* M01_A00_EXTRACT_DATAS_IN::M_DATAS_IN_ODO */s_datas_in_odo *M_DATAS_IN_ODO,
  /* M01_A00_EXTRACT_DATAS_IN::M_DATAS_IN_RADIO */s_datas_in_radio *M_DATAS_IN_RADIO,
  /* M01_A00_EXTRACT_DATAS_IN::M_DATAS_IN_BTM */s_datas_in_btm *M_DATAS_IN_BTM,
  /* M01_A00_EXTRACT_DATAS_IN::M_DATAS_IN_DMI */s_datas_in_dmi *M_DATAS_IN_DMI,
  /* M01_A00_EXTRACT_DATAS_IN::D_DISTANCE_ODO */kcg_int *D_DISTANCE_ODO,
  /* M01_A00_EXTRACT_DATAS_IN::Q_DRIVER_ACK_OS_MODE */kcg_bool *Q_DRIVER_ACK_OS_MODE,
  /* M01_A00_EXTRACT_DATAS_IN::NID_LRBG_BTM */kcg_int *NID_LRBG_BTM,
  /* M01_A00_EXTRACT_DATAS_IN::M_OS_AREA_BTM */s_os_area *M_OS_AREA_BTM,
  /* M01_A00_EXTRACT_DATAS_IN::M_GEO_POS_INFO_BTM */s_geo_pos_info *M_GEO_POS_INFO_BTM,
  /* M01_A00_EXTRACT_DATAS_IN::M_OS_AREA_RADIO */s_os_area *M_OS_AREA_RADIO,
  /* M01_A00_EXTRACT_DATAS_IN::M_GEO_POS_INFO_RADIO */s_geo_pos_info *M_GEO_POS_INFO_RADIO)
{
  (*M_OS_AREA_RADIO).D_START_OS_AREA =
    (*M_DATAS_IN_RADIO).M_PACKET_MODE_PROFILE.D_MAMODE;
  (*M_OS_AREA_RADIO).M_MAMODE =
    (*M_DATAS_IN_RADIO).M_PACKET_MODE_PROFILE.M_MAMODE;
  (*M_OS_AREA_RADIO).V_OS_AREA =
    (*M_DATAS_IN_RADIO).M_PACKET_MODE_PROFILE.V_MAMODE;
  (*M_OS_AREA_RADIO).L_OS_AREA =
    (*M_DATAS_IN_RADIO).M_PACKET_MODE_PROFILE.L_MAMODE;
  (*M_OS_AREA_RADIO).L_ACK_OS_AREA =
    (*M_DATAS_IN_RADIO).M_PACKET_MODE_PROFILE.L_ACKMAMODE;
  (*M_OS_AREA_BTM).D_START_OS_AREA =
    (*M_DATAS_IN_BTM).M_PACKET_MODE_PROFILE.D_MAMODE;
  (*M_OS_AREA_BTM).M_MAMODE = (*M_DATAS_IN_BTM).M_PACKET_MODE_PROFILE.M_MAMODE;
  (*M_OS_AREA_BTM).V_OS_AREA = (*M_DATAS_IN_BTM).M_PACKET_MODE_PROFILE.V_MAMODE;
  (*M_OS_AREA_BTM).L_OS_AREA = (*M_DATAS_IN_BTM).M_PACKET_MODE_PROFILE.L_MAMODE;
  (*M_OS_AREA_BTM).L_ACK_OS_AREA =
    (*M_DATAS_IN_BTM).M_PACKET_MODE_PROFILE.L_ACKMAMODE;
  (*M_GEO_POS_INFO_RADIO).NID_BG =
    (*M_DATAS_IN_RADIO).M_PACKET_GEO_POS_INFO.NID_BG;
  (*M_GEO_POS_INFO_RADIO).D_POSOFF =
    (*M_DATAS_IN_RADIO).M_PACKET_GEO_POS_INFO.D_POSOFF;
  (*M_GEO_POS_INFO_RADIO).M_POSITION =
    (*M_DATAS_IN_RADIO).M_PACKET_GEO_POS_INFO.M_POSITION;
  (*M_GEO_POS_INFO_BTM).NID_BG = (*M_DATAS_IN_BTM).M_PACKET_GEO_POS_INFO.NID_BG;
  (*M_GEO_POS_INFO_BTM).D_POSOFF =
    (*M_DATAS_IN_BTM).M_PACKET_GEO_POS_INFO.D_POSOFF;
  (*M_GEO_POS_INFO_BTM).M_POSITION =
    (*M_DATAS_IN_BTM).M_PACKET_GEO_POS_INFO.M_POSITION;
  *NID_LRBG_BTM = (*M_DATAS_IN_BTM).NID_LRBG_BTM;
  *Q_DRIVER_ACK_OS_MODE = (*M_DATAS_IN_DMI).Q_DRIVER_ACK_OS_MODE;
  *D_DISTANCE_ODO = (*M_DATAS_IN_ODO).D_DISTANCE_ODO;
}

/* $*************** KCG Version 6.1.3 (build i6) ****************
** M01_A00_EXTRACT_DATAS_IN.c
** Generation date: 2013-10-16T13:43:10
*************************************************************$ */

